# _config.yml

# _config.yml (add this new section, or integrate into an existing one)

# -----------------------------------------------------------------------------
# SITE LOOK & FEEL - Template user can customize these
# -----------------------------------------------------------------------------
site_look:
  site_background_color: "#2c3e50"  # A deep, modern dark blue/charcoal
  site_text_color: "#ecf0f1"        # A light, soft white/grey
  link_color: "#3498db"             # A bright, clear blue for links
  link_hover_color: "#2980b9"       # A slightly darker blue for link hover

# Site Meta (Template User can adjust these for their specific memorial site)
title: "A Memorial Tribute"
description: "A private space to remember and share memories of our beloved."
baseurl: "/Memorial-Template" # Crucial for sites not at the root of a domain
url: "https://mangoredditplayer.github.io/Memorial-Template" # Removed trailing slash

# -----------------------------------------------------------------------------
# MEMORIAL CONFIGURATION - Template user MUST edit this section
# -----------------------------------------------------------------------------
memorial_settings:
  deceased_name: "Replace with Loved One's Name" # Full name to display throughout the site
  site_password: "asdf123" # IMPORTANT: Template user must change this password!
  # Optional: Add more configurable fields later like:
  # welcome_message: "Welcome to this space dedicated to..."
  # birth_date: "Month Day, Year"
  # passing_date: "Month Day, Year"


# -----------------------------------------------------------------------------
# THIRD-PARTY SERVICE CONFIGURATION (for Memorial Wall comments/submissions)
# -----------------------------------------------------------------------------
# Example for Disqus (template user gets this from their Disqus account)
# If not using Disqus, this can be removed or adapted for another service.
disqus_shortname: "swo-memorial-template" # e.g., your-memorial-shortname (leave blank if not used initially)

# -----------------------------------------------------------------------------
# Jekyll Build Settings
# -----------------------------------------------------------------------------
theme: minima # A clean, minimal theme. You can change this later if desired.
              # To use a theme, you might need to add it to your Gemfile (see Step 1.2)

plugins:
  - jekyll-feed # For an RSS feed, optional but good practice
  # - jekyll-seo-tag # For better SEO, optional

# Files/folders to exclude from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - MODERATOR_GUIDE.md # We'll create this later, it's not part of the live site
  - LICENSE